version: '3'
services:
  install:
    image: node:12
    working_dir: /app
    volumes:
      - ./:/app
    command: 'yarn install --frozen-lockfile'

  build:
    image: node:12
    working_dir: /app
    volumes:
      - ./:/app
    command: 'yarn run build'

  start:
    image: node:12
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 1234:1234
      - 30000:30000
    command: 'yarn run start'
